2024-07-28 12:01:56.154 [info] Experiment 'pythonCreateEnvOnPipInstall' is active
2024-07-28 12:01:56.154 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-07-28 12:01:56.154 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-07-28 12:01:56.154 [info] Experiment 'pythonTestAdapter' is active
2024-07-28 12:01:56.154 [error] Reading directory to watch failed [Error: ENOENT: no such file or directory, scandir '/home/vicky/weather/weatherproject/.pixi/envs'
	at Object.readdirSync (node:fs:1529:3)
	at t.readdirSync (node:electron/js2c/node_init:2:11289)
	at /home/vicky/.vscode/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:574598
	at /home/vicky/.vscode/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:574789
	at Array.map (<anonymous>)
	at d.initWatchers (/home/vicky/.vscode/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:574507)
	at async d.ensureWatchersReady (/home/vicky/.vscode/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:536827)] {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/vicky/weather/weatherproject/.pixi/envs'
}
2024-07-28 12:01:56.154 [error] Dir "/home/vicky/weather/weatherproject/.pixi/envs" is not watchable (directory does not exist)
2024-07-28 12:01:56.154 [info] Default formatter is set to null for workspace /home/vicky/weather/weatherproject
2024-07-28 12:01:56.154 [info] Python interpreter path: /usr/bin/python
2024-07-28 12:01:56.333 [info] > pyenv which python
2024-07-28 12:01:56.333 [info] cwd: .
2024-07-28 12:01:57.362 [info] > pixi --version
2024-07-28 12:01:57.363 [error] [Error: spawn pixi ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:284:19)
	at onErrorNT (node:internal/child_process:477:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pixi',
  path: 'pixi',
  spawnargs: [ '--version' ]
}
2024-07-28 12:01:57.363 [warning] could not find a pixi interpreter for the interpreter at /usr/bin/python
2024-07-28 12:01:59.670 [info] Starting Pylance language server.
